name: Deploy static site

on:
  push:
    branches: [ "main" ]   # деплой при пуше в main
  workflow_dispatch:        # запуск вручную

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install rsync & ssh
        run: sudo apt-get update && sudo apt-get install -y rsync openssh-client

      - name: Setup SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          # правильный порядок аргументов: сначала -p, потом host
          ssh-keyscan -p ${SSH_PORT:-22} -H $DEPLOY_HOST >> ~/.ssh/known_hosts

      - name: Deploy via rsync
        env:
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
        run: |
          rsync -az --delete \
            --exclude '.git' \
            --exclude '.github' \
            -e "ssh -p ${SSH_PORT:-22}" \
            ./ $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH/
